version: '3.5'

services:
  diagrams:
    image: "jgraph/drawio"
    restart: always
    networks:
      - overlay
  scratch:
    image: "leejoneshane/docker-scratch3"
    restart: always
    networks:
      - overlay
  barcodegenerator:
    image: "padiazg/barcode-generator"
    restart: always
    networks:
      - overlay
  vscode:
    image: ghcr.io/linuxserver/code-server
    env_file: vscode.env
    restart: always
    networks:
      - overlay
  calibre:
    image: ghcr.io/linuxserver/calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 7127:8080
      - 7128:8081
    restart: unless-stopped
    networks:
      - overlay
networks:
    overlay:
        driver: overlay