 services:
  app:
     image: nextcloud:16-apache
     restart: always
     ports:
       - "3040:80"
     depends_on:
       - db
     env_file: nextcloud.env
     volumes:
       - ./mountPoints/nextcloud/data:/var/www/html
  db:
     image: mariadb:10.3
     restart: always
     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
     env_file: nextcloud.env
     expose:
       - '3306'
     volumes:
       - ./mountPoints/nextcloud/db:/var/lib/mysql
