version: '3.5'

services:
  registry_mirror:
    hostname: registry_mirror
    restart: ${RESTART_POLICY}
    build:
      context: src/registry
      dockerfile: Dockerfile
      args:
        - "apiPort=5000"
        - "metricsPort=5001"
    env_file: registry.env
    ports:
      - "5002:5000"
      - "5003:5001"
    volumes:
      - registryMirror_data:/var/lib/registry
      - registry_certs:/certs
      - ./mountPoints/registryMirror/config.yml:/etc/docker/registry/config.yml
  registry:
    hostname: registry_app
    restart: ${RESTART_POLICY}
    build:
      context: src/registry
      dockerfile: Dockerfile
      args:
        - "basicAuthUsername=${DOCKER_REGISTRY_AUTHUSER}"
        - "basicAuthPassword=${DOCKER_REGISTRY_AUTHPASSWORD}"
        - "apiPort=5000"
        - "metricsPort=5001"
    env_file: registry.env
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - registry_data:/var/lib/registry
      - registry_certs:/certs
      - ./mountPoints/registry/config.yml:/etc/docker/registry/config.yml
      - registry_auth:/auth
    labels:
      # Adding this label means this container should be stopped while it's being backed up:
      - "docker-volume-backup.stop-during-backup=true"
   # This is a cool image to help take backups of volumes. You can take a manual backup of the running volume by executing:
   # docker-compose exec backup ./backup.sh
   # See https://github.com/futurice/docker-volume-backup for more info
  registry_backup:
    depends_on:
      - registry
    image: futurice/docker-volume-backup
    restart: ${RESTART_POLICY}
    environment:
      BACKUP_CRON_EXPRESSION: "0 20 * * *"
      HTTP_PROXY: $HTTP_PROXY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allow use of the "stop-during-backup" feature
      - registry_data:/backup/registry_data:ro    # Mount the registry data volume (as read-only)
      - ./backups/registry:/archive                      # Mount a local folder as the backup archive
  registryui:
    hostname: registryui
    depends_on:
      - registry
    build:
      context: src/registryUI
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY}
    env_file: registry.env
    links:
      - registry:registry
    volumes:
      - ./mountPoints/registryUI/config.yml:/opt/config.yml
volumes:
  registry_data:
  registry_certs:
  registry_requested_certs:
  registry_auth:
  registryMirror_data:
  registryui_reverseproxy_certs: