services:
  baget:
    image: loicsharma/baget
    ports:
      - 5555:80
    env_file: baget.env
    volumes: 
      - baget_db:/var/baget/db
      - baget_packages:/var/baget/packages
      - ./mountPoints/baget/appsettings.json:/app/appsettings.json

volumes:
  baget_db:
  baget_packages: