version: '3.5'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    env_file: moodle.env
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - overlay
  moodle:
    image: docker.io/bitnami/moodle:3
    env_file: moodle.env
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - overlay
  # This is a cool image to help take backups of volumes. You can take a manual backup of the running volume by executing:
  # docker-compose exec backup ./backup.sh
  # See https://github.com/futurice/docker-volume-backup for more info
  moodle_data_backup:
    depends_on:
      - moodle
    image: futurice/docker-volume-backup:2.3.0
    restart: 'unless-stopped'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allow use of the "stop-during-backup" feature
      - moodle_data:/backup/moodle_data:ro
      - ./backups/moodle_data:/archive                      # Mount a local folder as the backup archive
    environment:
        BACKUP_CRON_EXPRESSION: "0 13 * * *"
    networks:
      - overlay
  mariadb_data_backup:
    depends_on:
      - mariadb
    image: futurice/docker-volume-backup:2.3.0
    restart: 'unless-stopped'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allow use of the "stop-during-backup" feature
      - mariadb_data:/backup/mariadb_data:ro
      - ./backups/mariadb_data:/archive                      # Mount a local folder as the backup archive
    environment:
      BACKUP_CRON_EXPRESSION: "0 13 * * *"
    networks:
      - overlay
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
networks:
    overlay:
        driver: overlay