
version: '3.5'

services:
  ca:
    image: cfssl/cfssl
    hostname: ca
    domainname: cfssl
    restart: ${RESTART_POLICY}
    container_name: ca
    volumes:
      - type: bind
        source: ./mountPoints/ca
        target: /ca
    healthcheck:
      test: curl --fail http://localhost:8888/api/v1/cfssl/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file: ca.env
    entrypoint: ["cfssl", "serve", "-ca", "/ca/docker.crt", "-ca-key", "/ca/docker.key", "-ca-bundle", "/ca/ca-bundle.crt", "-address", "0.0.0.0", "-loglevel", "0"] #, "-config", "/ca/config.json"]
  certgetter:
    depends_on:
      - ca
    env_file: ca.env
    build:
      context: ./src/ca
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY}
    volumes:
      - registry_certs:/mnt/registry_certs
      - grafana_certs:/mnt/grafana_certs
      - ca_certs:/mnt/ca_certs
      - registryui_certs:/mnt/registryui_certs
      - squid_certs:/mnt/squid_certs
      - ldap_certs:/mnt/ldap_certs
      - nextcloud_certs:/mnt/nextcloud_certs
      - kibana_certs:/mnt/kibana_certs
      - elastic_certs:/mnt/elastic_certs
      - diagrams_certs:/mnt/diagrams_certs
      - nagios_certs:/mnt/nagios_certs
      - prometheus_certs:/mnt/prometheus_certs
      - prometheusblackbox_certs:/mnt/prometheusblackbox_certs
      - vscode_certs:/mnt/vscode_certs
      - calibre_certs:/mnt/calibre_certs
      - mineos_certs:/mnt/mineos_certs
      - scratch_certs:/mnt/scratch_certs
    # Tried real hard to run this script with parameters, specifically the array of PSObjects. I could shell in and run the command below just fine, but could not get it in a place for the entrypoint
    # pwsh -command "& /work/New-CFSSL_Certificate.ps1 -certRequests ([PSCustomObject]@{name = 'registry'; hosts = @('ImageRegistry','localhost','127.0.0.1')},[PSCustomObject]@{name = 'grafana'; hosts = @('grafana','localhost','127.0.0.1')})"
    entrypoint: ["pwsh", "/work/New-CFSSL_Certificate.ps1"]
    healthcheck:
      test: ["CMD", "pwsh", "-c", "Test-Path", "/certs/cert.crt"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
  dns: 
    image: coredns/coredns
    ports:
        - 53:53/udp
        - 5353:5353
        - 5392:9253
    volumes:
      - ./mountPoints/coredns:/root
    command: -conf /root/Corefile
    env_file: ca.env
    restart: ${RESTART_POLICY}
  ingress:
    image: nginx:1.19-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./mountPoints/ingress/basicAuth:/etc/nginx/basicAuth
      - ./mountPoints/ingress/nginx.conf:/etc/nginx/nginx.conf
      - ca_certs:/etc/nginx/conf.d/ca
      - grafana_certs:/etc/nginx/conf.d/grafana
      - ldap_certs:/etc/nginx/conf.d/ldap
      - nextcloud_certs:/etc/nginx/conf.d/nextcloud
      - kibana_certs:/etc/nginx/conf.d/kibana
      - elastic_certs:/etc/nginx/conf.d/elastic
      - diagrams_certs:/etc/nginx/conf.d/diagrams
      - nagios_certs:/etc/nginx/conf.d/nagios
      - prometheus_certs:/etc/nginx/conf.d/prometheus
      - prometheusblackbox_certs:/etc/nginx/conf.d/prometheusblackbox
      - registryui_certs:/etc/nginx/conf.d/registryui
      - registry_certs:/etc/nginx/conf.d/registry
      - vscode_certs:/etc/nginx/conf.d/vscode
      - calibre_certs:/etc/nginx/conf.d/calibre
      - mineos_certs:/etc/nginx/conf.d/mineos
      - scratch_certs:/etc/nginx/conf.d/scratch
    restart: ${RESTART_POLICY}
  myvault:
      image: vault
      container_name: myvault
      ports:
        - "127.0.0.1:8201:8200"
      volumes:
        - ./mountPoints/vault/file:/vault/file:rw
        - ./mountPoints/vault/config:/vault/config:rw
      cap_add:
        - IPC_LOCK
      entrypoint: vault server -config=/vault/config/vault.json
volumes:
  registry_certs:
  registry_requested_certs:
  registry_auth:
  grafana_data:
  grafana_plugins:
  grafana_provisiong:
  grafana_home:
  grafana_logs:
  grafana_certs:
  squid_cache:
  squid_log:
  squid_certs:
  ca_certs:
  registryui_certs:
  ldap_certs:
  dhcp_leases:
  nextcloud_certs:
  elastic_certs:
  kibana_certs:
  diagrams_certs:
  nagios_certs:
  prometheus_certs:
  prometheusblackbox_certs:
  vscode_certs:
  calibre_certs:
  mineos_certs:
  scratch_certs: