version: '3.5'

services:
  factorio_sandbox:
    hostname: game
    image: factoriotools/factorio
    environment: 
        - UPDATE_MODS_ON_START=false
        - GENERATE_NEW_SAVE=false
        - PORT=9102
        #- SAVE_NAME='Demetrius and Dad'
    network_mode: host
    volumes:
      - ./mountPoint/factorio_sandbox:/factorio  
    restart: always 
  factorio_sandbox_exporter:
    image: prom/node-exporter
    command: --collector.textfile.directory=/textfiles
    volumes:
      - ./mountPoint/factorio_sandbox/script-output/graftorio2:/textfiles # Windows
      # - ~/Library/Application Support/factorio/script-output/graftorio/:/textfiles # macOS
      # - /opt/factorio/script-output/graftorio:/textfiles # Linux
    ports:
      - 9103:9100
    restart: always