version: '3.5'

services:
  game:
    hostname: game
    image: factoriotools/factorio
    environment: 
        - UPDATE_MODS_ON_START=true
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - game_data:/factorio   
    labels:
      # Adding this label means this container should be stopped while it's being backed up:
      - "docker-volume-backup.stop-during-backup=true"
   # This is a cool image to help take backups of volumes. You can take a manual backup of the running volume by executing:
   # docker-compose exec game_backup ./backup.sh
   # See https://github.com/futurice/docker-volume-backup for more info
  game_backup:
    depends_on:
      - game
    image: futurice/docker-volume-backup
    restart: 'unless-stopped'
    environment:
      - "BACKUP_CRON_EXPRESSION=*0 5 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allow use of the "stop-during-backup" feature
      - game_data:/backup/game_data:ro    # Mount the registry data volume (as read-only)
      - ./backups/game_data:/archive                      # Mount a local folder as the backup archive
volumes:
  game_data:
