---
- hosts: all
  remote_user: pi
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Update all packages to the latest version
      apt:
        upgrade: dist