--- 
  global: 
    evaluation_interval: 15s
    external_labels: 
      monitor: codelab-monitor
    scrape_interval: 15s
    scrape_timeout: 10s
  scrape_configs: 
    - job_name: prometheus
      static_configs: 
        - 
          targets: 
            - "localhost:9090"    
    - job_name: registry
      metrics_path: /metrics/
      dns_sd_configs: #This lets us bind to the dns entries for the swarm/gathering of containers
        - names:
          - registry
          type: A
          port: 5001
    - job_name: 'docker-workers'
      scrape_interval: 15s
      metrics_path: /metrics
      static_configs:
        - targets: [localhost:50501']
    - job_name: 'squid'
      scrape_interval: 15s
      static_configs:
        - targets: [localhost:9301']
