--- 
  global: 
    evaluation_interval: 15s
    scrape_interval: 15s
    scrape_timeout: 10s
  scrape_configs: 
    - job_name: coredns
      metrics_path: /metrics
      static_configs: 
        - targets: [ 'dns.mcd.com:5392' ]
