#cloud-config
# Setup a Ubuntu VM in azure with docker and powershell to allow me to bootstrap a jitsi instance
# DO NOT USE THIS IN PRODUCTION
# Copied from https://stackoverflow.com/questions/54916851/install-docker-and-docker-compose-on-azure-using-cloud-init
package_update: true

# Setup swap memory
disk_setup:
    ephemeral0:
        table_type: mbr
        layout: [66, [33, 82]]
        overwrite: True
fs_setup:
    - device: ephemeral0.1
      filesystem: ext4
    - device: ephemeral0.2
      filesystem: swap
mounts:
    - ["ephemeral0.1", "/mnt"]
    - ["ephemeral0.2", "none", "swap", "sw", "0", "0"]

# Enable Docker's swap limit support
bootcmd:
    - [ sh, -c, 'sudo echo GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1" >> /etc/default/grub' ]
    - [ sh, -c, 'sudo update-grub' ]
    - [ cloud-init-per, once, mymkfs, mkfs, /dev/vdb ]

# Install docker and docker-compose
runcmd:
    - [ sh, -c, 'curl -sSL https://get.docker.com/ | sh' ]
    - [ sh, -c, 'sudo curl -L https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep "tag_name" | cut -d \" -f4)/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose' ]
    - [ sh, -c, 'sudo chmod +x /usr/local/bin/docker-compose' ]
    - [ sh,-c,'sudo snap install powershell --classic']
    - [ sh,-c, 'mkdir -p /opt/jitsi']
    - [ sh,-c, 'git clone https://github.com/jitsi/docker-jitsi-meet'] 
# Add default auto created user to docker group
system_info:
    default_user:
        groups: [docker]